version: 1
default_environment: dev
send_anonymous_usage_stats: false
project_id: 33080f0b-2d0f-4fba-b7f1-727bbf080f91

plugins:
  extractors:
  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
  - name: tap-smoke-test
    namespace: tap_smoke_test
    pip_url: git+https://github.com/meltano/tap-smoke-test.git
    executable: tap-smoke-test
    capabilities:
    - discover
    - catalog
    settings:
    - name: schema_inference_record_count
      kind: integer
    - name: streams
      kind: array
  - name: people
    namespace: people
    executable: scripts/people.sh
  loaders:
  - name: target-sqlite
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/target-sqlite.git
    config:
      batch_size: 200
      database: output/$MELTANO_EXTRACTOR_NAMESPACE.db
  mappers:
  - name: meltano-map-transformer
    pip_url: .
    executable: meltano-map-transform
    settings:
    - name: stream_maps
      kind: object
    mappings:
    - name: hash_email
      config:
        stream_maps:
          customers:
            id: id
            email:      # drop the PII field from RECORD and SCHEMA messages
            email_domain: email.split('@')[-1]
            email_hash: md5(config['hash_seed'] + email)
            __else__: null
        stream_map_config:
          hash_seed: 01AWZh7A6DzGm6iJZZ2T
    - name: whitelist
      config:
        stream_maps:
          # Whitelist `id` and `description` fields, drop all others
          animals:
            id: id
            description: description
            __else__: null
    - name: flatten
      config:
        stream_maps: {}
        flattening_enabled: true
        flattening_max_depth: 1
environments:
- name: dev
  config:
    plugins:
      extractors:
      - name: tap-csv
        config:
          files:
          - entity: customers
            path: fixtures/customers.csv
            keys: [id]
      - name: tap-smoke-test
        config:
          schema_inference_record_count: 5
          streams:
          - stream_name: animals
            input_filename: fixtures/animals-data.jsonl
